// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Use a safe fallback URL if missing to prevent initialization crash
// But ensure it looks like a valid Supabase URL structure to avoid client-side validation errors
const safeUrl = SUPABASE_URL && SUPABASE_URL.startsWith('http') ? SUPABASE_URL : "https://your-project.supabase.co";
const safeKey = SUPABASE_PUBLISHABLE_KEY || "your-anon-key";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("ENVIRONMENT ERROR: Supabase credentials (VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY) are missing in project settings.");
}

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_URL.startsWith('http') && SUPABASE_PUBLISHABLE_KEY);

export const supabase = createClient<Database>(safeUrl, safeKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});